#define FLOATPOS                                                  \
    &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26x -26y"}}),     \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "  0x -26y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26x -26y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26x   0y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26x   0y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26x  26y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "  0x  26y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26x  26y"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26a -26a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "  0a -26a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26a -26a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26a   0a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26a   0a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26a  26a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "  0a  26a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26a  26a"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26w -26h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "  0w -26h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26w -26h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26w   0h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "800W 800H"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26w   0h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-26w  26h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "  0w  26h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 26w  26h"}}), \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-1p -1p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 0p -1p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 1p -1p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-1p  0p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 0p  0p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 1p  0p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = "-1p  1p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 0p  1p"}}),   \
        &((Keychord){1, {{0, 0}}, floatpos, {.v = " 1p  1p"}})
